name: ✨ 機能リクエスト
description: 新機能のアイデアを提案する
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        新しい機能の提案ありがとうございます！以下の項目を埋めてください。

  - type: input
    id: title
    attributes:
      label: 機能のタイトル
      description: 提案する機能のタイトルを記載してください
      placeholder: '例: ダークモードの追加'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 機能の詳細
      description: 提案する機能の具体的な内容や背景を記載してください
      placeholder: '例: ユーザーが夜間でも目に優しいUIを利用できるようにする'
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 機能のメリット
      description: この機能を導入することで得られる利点を記載してください
      placeholder: '例: ユーザー満足度の向上、視認性の改善'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決策や機能案があれば記載してください
      placeholder: '例: テーマのカスタマイズ機能'
    validations:
      required: false
